- name: Commit and push status
  env:
    GH_TOKEN: ${{ secrets.PUSH_TOKEN }}  # 使用PAT
  run: |
    git config --global user.name "GitHub Actions Bot"
    git config --global user.email "actions-bot@users.noreply.github.com"
    git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    git add push_state.json
    git diff --quiet && git diff --cached --quiet || git commit -m "Update push status [skip ci]"
    git push

on:
  schedule:
    - cron: '30 1 * * 1-5'       # 09:30 CST
    - cron: '0,30 2 * * 1-5'     # 10:00-10:30 CST
    - cron: '0,30 3 * * 1-5'     # 11:00-11:30 CST
    - cron: '0,30 5 * * 1-5'     # 13:00-13:30 CST
    - cron: '0,30 6 * * 1-5'     # 14:00-14:30 CST
    - cron: '0 7 * * 1-5'        # 15:00 CST
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    env:
      PUSHDEER_PUSHKEY: ${{ secrets.PUSHDEER_PUSHKEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Initialize state file
      run: |
        if [ ! -f push_state.json ]; then
          echo '{"last_push": null, "push_count": 0}' > push_state.json
        fi

    - name: Run stock monitor
      run: python stock_alert.py

    - name: Commit and push status
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@users.noreply.github.com"
        git add push_state.json
        git diff --quiet && git diff --cached --quiet || git commit -m "Update push status [skip ci]"
        git push
