name: Stock Market Alert

on:
  schedule:
    - cron: '30 1 * * 1-5'
    - cron: '0,30 2 * * 1-5'
    - cron: '0,30 3 * * 1-5'
    - cron: '0,30 5 * * 1-5'
    - cron: '0,30 6 * * 1-5'
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-stock:
    runs-on: ubuntu-latest
    env:
      PUSHDEER_PUSHKEY: ${{ secrets.PUSHDEER_PUSHKEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PUSH_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Initialize state file
      run: |
        if [ ! -f push_state.json ]; then
          echo '{"last_push": null, "push_count": 0}' > push_state.json
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git add push_state.json
          git commit -m "Initialize state file" || true
        fi

    - name: Run stock monitor
      run: python stock_alert.py

    - name: Commit and push status
      env:
        GH_TOKEN: ${{ secrets.PUSH_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:$GH_TOKEN | base64)"
        git add push_state.json
        if ! git diff --quiet || ! git diff --cached --quiet; then
          git commit -m "Update push status [skip ci]"
          for i in {1..3}; do
            git push && break || sleep 5
          done
        fi
